[2022-08-01 15:54:58,068] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: pipeline.download_data 2022-07-30T00:00:00+00:00 [queued]>
[2022-08-01 15:54:58,075] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: pipeline.download_data 2022-07-30T00:00:00+00:00 [queued]>
[2022-08-01 15:54:58,076] {{taskinstance.py:866}} INFO - 
--------------------------------------------------------------------------------
[2022-08-01 15:54:58,076] {{taskinstance.py:867}} INFO - Starting attempt 1 of 1
[2022-08-01 15:54:58,076] {{taskinstance.py:868}} INFO - 
--------------------------------------------------------------------------------
[2022-08-01 15:54:58,083] {{taskinstance.py:887}} INFO - Executing <Task(BashOperator): download_data> on 2022-07-30T00:00:00+00:00
[2022-08-01 15:54:58,086] {{standard_task_runner.py:53}} INFO - Started process 205 to run task
[2022-08-01 15:54:58,125] {{logging_mixin.py:112}} INFO - Running %s on host %s <TaskInstance: pipeline.download_data 2022-07-30T00:00:00+00:00 [running]> 72435ff738b6
[2022-08-01 15:54:58,137] {{bash_operator.py:82}} INFO - Tmp dir root location: 
 /tmp
[2022-08-01 15:54:58,137] {{bash_operator.py:105}} INFO - Temporary script location: /tmp/airflowtmpglqcbggy/download_datati9vu0ts
[2022-08-01 15:54:58,137] {{bash_operator.py:115}} INFO - Running command: 
  python3 $AIRFLOW_HOME/airflow/step1/data_download.py
[2022-08-01 15:54:58,143] {{bash_operator.py:122}} INFO - Output:
[2022-08-01 15:54:58,165] {{bash_operator.py:126}} INFO - python3: can't open file '/usr/local/airflow/airflow/step1/data_download.py': [Errno 2] No such file or directory
[2022-08-01 15:54:58,167] {{bash_operator.py:130}} INFO - Command exited with return code 2
[2022-08-01 15:54:58,172] {{taskinstance.py:1128}} ERROR - Bash command failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 134, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2022-08-01 15:54:58,174] {{taskinstance.py:1185}} INFO - Marking task as FAILED.dag_id=pipeline, task_id=download_data, execution_date=20220730T000000, start_date=20220801T155458, end_date=20220801T155458
[2022-08-01 15:55:08,064] {{logging_mixin.py:112}} INFO - [2022-08-01 15:55:08,064] {{local_task_job.py:103}} INFO - Task exited with return code 1
[2022-08-01 16:04:20,473] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: pipeline.download_data 2022-07-30T00:00:00+00:00 [queued]>
[2022-08-01 16:04:20,480] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: pipeline.download_data 2022-07-30T00:00:00+00:00 [queued]>
[2022-08-01 16:04:20,480] {{taskinstance.py:866}} INFO - 
--------------------------------------------------------------------------------
[2022-08-01 16:04:20,480] {{taskinstance.py:867}} INFO - Starting attempt 1 of 1
[2022-08-01 16:04:20,480] {{taskinstance.py:868}} INFO - 
--------------------------------------------------------------------------------
[2022-08-01 16:04:20,489] {{taskinstance.py:887}} INFO - Executing <Task(BashOperator): download_data> on 2022-07-30T00:00:00+00:00
[2022-08-01 16:04:20,491] {{standard_task_runner.py:53}} INFO - Started process 97 to run task
[2022-08-01 16:04:20,529] {{logging_mixin.py:112}} INFO - Running %s on host %s <TaskInstance: pipeline.download_data 2022-07-30T00:00:00+00:00 [running]> 11dd07060667
[2022-08-01 16:04:20,540] {{bash_operator.py:82}} INFO - Tmp dir root location: 
 /tmp
[2022-08-01 16:04:20,541] {{bash_operator.py:105}} INFO - Temporary script location: /tmp/airflowtmpjgejz83y/download_dataqhysaswm
[2022-08-01 16:04:20,541] {{bash_operator.py:115}} INFO - Running command: 
  python3 $AIRFLOW_HOME/step1/data_download.py
[2022-08-01 16:04:20,545] {{bash_operator.py:122}} INFO - Output:
[2022-08-01 16:04:20,562] {{bash_operator.py:126}} INFO - python3: can't open file '/usr/local/airflow/step1/data_download.py': [Errno 2] No such file or directory
[2022-08-01 16:04:20,565] {{bash_operator.py:130}} INFO - Command exited with return code 2
[2022-08-01 16:04:20,569] {{taskinstance.py:1128}} ERROR - Bash command failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 134, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2022-08-01 16:04:20,570] {{taskinstance.py:1185}} INFO - Marking task as FAILED.dag_id=pipeline, task_id=download_data, execution_date=20220730T000000, start_date=20220801T160420, end_date=20220801T160420
[2022-08-01 16:04:30,469] {{logging_mixin.py:112}} INFO - [2022-08-01 16:04:30,469] {{local_task_job.py:103}} INFO - Task exited with return code 1
[2022-08-01 16:11:05,035] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: pipeline.download_data 2022-07-30T00:00:00+00:00 [queued]>
[2022-08-01 16:11:05,042] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: pipeline.download_data 2022-07-30T00:00:00+00:00 [queued]>
[2022-08-01 16:11:05,043] {{taskinstance.py:866}} INFO - 
--------------------------------------------------------------------------------
[2022-08-01 16:11:05,043] {{taskinstance.py:867}} INFO - Starting attempt 1 of 1
[2022-08-01 16:11:05,043] {{taskinstance.py:868}} INFO - 
--------------------------------------------------------------------------------
[2022-08-01 16:11:05,050] {{taskinstance.py:887}} INFO - Executing <Task(BashOperator): download_data> on 2022-07-30T00:00:00+00:00
[2022-08-01 16:11:05,052] {{standard_task_runner.py:53}} INFO - Started process 97 to run task
[2022-08-01 16:11:05,091] {{logging_mixin.py:112}} INFO - Running %s on host %s <TaskInstance: pipeline.download_data 2022-07-30T00:00:00+00:00 [running]> f45377789134
[2022-08-01 16:11:05,104] {{bash_operator.py:82}} INFO - Tmp dir root location: 
 /tmp
[2022-08-01 16:11:05,105] {{bash_operator.py:105}} INFO - Temporary script location: /tmp/airflowtmppnyi_pfx/download_dataihtcf1x8
[2022-08-01 16:11:05,105] {{bash_operator.py:115}} INFO - Running command:  cd $AIRFLOW_HOME/step1
                        python3 data_download.py
[2022-08-01 16:11:05,110] {{bash_operator.py:122}} INFO - Output:
[2022-08-01 16:11:05,111] {{bash_operator.py:126}} INFO - /tmp/airflowtmppnyi_pfx/download_dataihtcf1x8: line 1: cd: /usr/local/airflow/step1: No such file or directory
[2022-08-01 16:11:05,129] {{bash_operator.py:126}} INFO - python3: can't open file 'data_download.py': [Errno 2] No such file or directory
[2022-08-01 16:11:05,131] {{bash_operator.py:130}} INFO - Command exited with return code 2
[2022-08-01 16:11:05,136] {{taskinstance.py:1128}} ERROR - Bash command failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 134, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2022-08-01 16:11:05,137] {{taskinstance.py:1185}} INFO - Marking task as FAILED.dag_id=pipeline, task_id=download_data, execution_date=20220730T000000, start_date=20220801T161105, end_date=20220801T161105
[2022-08-01 16:11:15,034] {{logging_mixin.py:112}} INFO - [2022-08-01 16:11:15,033] {{local_task_job.py:103}} INFO - Task exited with return code 1
