[2022-08-01 15:55:10,634] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: pipeline.download_data 2022-07-31T00:00:00+00:00 [queued]>
[2022-08-01 15:55:10,642] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: pipeline.download_data 2022-07-31T00:00:00+00:00 [queued]>
[2022-08-01 15:55:10,642] {{taskinstance.py:866}} INFO - 
--------------------------------------------------------------------------------
[2022-08-01 15:55:10,642] {{taskinstance.py:867}} INFO - Starting attempt 1 of 1
[2022-08-01 15:55:10,642] {{taskinstance.py:868}} INFO - 
--------------------------------------------------------------------------------
[2022-08-01 15:55:10,651] {{taskinstance.py:887}} INFO - Executing <Task(BashOperator): download_data> on 2022-07-31T00:00:00+00:00
[2022-08-01 15:55:10,654] {{standard_task_runner.py:53}} INFO - Started process 219 to run task
[2022-08-01 15:55:10,694] {{logging_mixin.py:112}} INFO - Running %s on host %s <TaskInstance: pipeline.download_data 2022-07-31T00:00:00+00:00 [running]> 72435ff738b6
[2022-08-01 15:55:10,706] {{bash_operator.py:82}} INFO - Tmp dir root location: 
 /tmp
[2022-08-01 15:55:10,707] {{bash_operator.py:105}} INFO - Temporary script location: /tmp/airflowtmp5wyyo29_/download_datadbsdrxcx
[2022-08-01 15:55:10,707] {{bash_operator.py:115}} INFO - Running command: 
  python3 $AIRFLOW_HOME/airflow/step1/data_download.py
[2022-08-01 15:55:10,712] {{bash_operator.py:122}} INFO - Output:
[2022-08-01 15:55:10,730] {{bash_operator.py:126}} INFO - python3: can't open file '/usr/local/airflow/airflow/step1/data_download.py': [Errno 2] No such file or directory
[2022-08-01 15:55:10,733] {{bash_operator.py:130}} INFO - Command exited with return code 2
[2022-08-01 15:55:10,738] {{taskinstance.py:1128}} ERROR - Bash command failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 134, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2022-08-01 15:55:10,739] {{taskinstance.py:1185}} INFO - Marking task as FAILED.dag_id=pipeline, task_id=download_data, execution_date=20220731T000000, start_date=20220801T155510, end_date=20220801T155510
[2022-08-01 15:55:20,626] {{logging_mixin.py:112}} INFO - [2022-08-01 15:55:20,626] {{local_task_job.py:103}} INFO - Task exited with return code 1
[2022-08-01 16:04:32,977] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: pipeline.download_data 2022-07-31T00:00:00+00:00 [queued]>
[2022-08-01 16:04:32,986] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: pipeline.download_data 2022-07-31T00:00:00+00:00 [queued]>
[2022-08-01 16:04:32,987] {{taskinstance.py:866}} INFO - 
--------------------------------------------------------------------------------
[2022-08-01 16:04:32,987] {{taskinstance.py:867}} INFO - Starting attempt 1 of 1
[2022-08-01 16:04:32,987] {{taskinstance.py:868}} INFO - 
--------------------------------------------------------------------------------
[2022-08-01 16:04:32,996] {{taskinstance.py:887}} INFO - Executing <Task(BashOperator): download_data> on 2022-07-31T00:00:00+00:00
[2022-08-01 16:04:32,998] {{standard_task_runner.py:53}} INFO - Started process 119 to run task
[2022-08-01 16:04:33,044] {{logging_mixin.py:112}} INFO - Running %s on host %s <TaskInstance: pipeline.download_data 2022-07-31T00:00:00+00:00 [running]> 11dd07060667
[2022-08-01 16:04:33,057] {{bash_operator.py:82}} INFO - Tmp dir root location: 
 /tmp
[2022-08-01 16:04:33,058] {{bash_operator.py:105}} INFO - Temporary script location: /tmp/airflowtmpi1hran3m/download_dataalafjika
[2022-08-01 16:04:33,058] {{bash_operator.py:115}} INFO - Running command: 
  python3 $AIRFLOW_HOME/step1/data_download.py
[2022-08-01 16:04:33,064] {{bash_operator.py:122}} INFO - Output:
[2022-08-01 16:04:33,087] {{bash_operator.py:126}} INFO - python3: can't open file '/usr/local/airflow/step1/data_download.py': [Errno 2] No such file or directory
[2022-08-01 16:04:33,092] {{bash_operator.py:130}} INFO - Command exited with return code 2
[2022-08-01 16:04:33,097] {{taskinstance.py:1128}} ERROR - Bash command failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 134, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2022-08-01 16:04:33,098] {{taskinstance.py:1185}} INFO - Marking task as FAILED.dag_id=pipeline, task_id=download_data, execution_date=20220731T000000, start_date=20220801T160432, end_date=20220801T160433
[2022-08-01 16:04:42,970] {{logging_mixin.py:112}} INFO - [2022-08-01 16:04:42,970] {{local_task_job.py:103}} INFO - Task exited with return code 1
[2022-08-01 16:11:17,437] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: pipeline.download_data 2022-07-31T00:00:00+00:00 [queued]>
[2022-08-01 16:11:17,445] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: pipeline.download_data 2022-07-31T00:00:00+00:00 [queued]>
[2022-08-01 16:11:17,445] {{taskinstance.py:866}} INFO - 
--------------------------------------------------------------------------------
[2022-08-01 16:11:17,445] {{taskinstance.py:867}} INFO - Starting attempt 1 of 1
[2022-08-01 16:11:17,445] {{taskinstance.py:868}} INFO - 
--------------------------------------------------------------------------------
[2022-08-01 16:11:17,453] {{taskinstance.py:887}} INFO - Executing <Task(BashOperator): download_data> on 2022-07-31T00:00:00+00:00
[2022-08-01 16:11:17,455] {{standard_task_runner.py:53}} INFO - Started process 119 to run task
[2022-08-01 16:11:17,494] {{logging_mixin.py:112}} INFO - Running %s on host %s <TaskInstance: pipeline.download_data 2022-07-31T00:00:00+00:00 [running]> f45377789134
[2022-08-01 16:11:17,505] {{bash_operator.py:82}} INFO - Tmp dir root location: 
 /tmp
[2022-08-01 16:11:17,505] {{bash_operator.py:105}} INFO - Temporary script location: /tmp/airflowtmpjr9htp2a/download_data536ijpwf
[2022-08-01 16:11:17,505] {{bash_operator.py:115}} INFO - Running command:  cd $AIRFLOW_HOME/step1
                        python3 data_download.py
[2022-08-01 16:11:17,510] {{bash_operator.py:122}} INFO - Output:
[2022-08-01 16:11:17,511] {{bash_operator.py:126}} INFO - /tmp/airflowtmpjr9htp2a/download_data536ijpwf: line 1: cd: /usr/local/airflow/step1: No such file or directory
[2022-08-01 16:11:17,527] {{bash_operator.py:126}} INFO - python3: can't open file 'data_download.py': [Errno 2] No such file or directory
[2022-08-01 16:11:17,530] {{bash_operator.py:130}} INFO - Command exited with return code 2
[2022-08-01 16:11:17,534] {{taskinstance.py:1128}} ERROR - Bash command failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 134, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2022-08-01 16:11:17,535] {{taskinstance.py:1185}} INFO - Marking task as FAILED.dag_id=pipeline, task_id=download_data, execution_date=20220731T000000, start_date=20220801T161117, end_date=20220801T161117
[2022-08-01 16:11:27,436] {{logging_mixin.py:112}} INFO - [2022-08-01 16:11:27,436] {{local_task_job.py:103}} INFO - Task exited with return code 1
