[2022-08-01 15:55:10,634] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: pipeline.download_data 2022-07-31T00:00:00+00:00 [queued]>
[2022-08-01 15:55:10,642] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: pipeline.download_data 2022-07-31T00:00:00+00:00 [queued]>
[2022-08-01 15:55:10,642] {{taskinstance.py:866}} INFO - 
--------------------------------------------------------------------------------
[2022-08-01 15:55:10,642] {{taskinstance.py:867}} INFO - Starting attempt 1 of 1
[2022-08-01 15:55:10,642] {{taskinstance.py:868}} INFO - 
--------------------------------------------------------------------------------
[2022-08-01 15:55:10,651] {{taskinstance.py:887}} INFO - Executing <Task(BashOperator): download_data> on 2022-07-31T00:00:00+00:00
[2022-08-01 15:55:10,654] {{standard_task_runner.py:53}} INFO - Started process 219 to run task
[2022-08-01 15:55:10,694] {{logging_mixin.py:112}} INFO - Running %s on host %s <TaskInstance: pipeline.download_data 2022-07-31T00:00:00+00:00 [running]> 72435ff738b6
[2022-08-01 15:55:10,706] {{bash_operator.py:82}} INFO - Tmp dir root location: 
 /tmp
[2022-08-01 15:55:10,707] {{bash_operator.py:105}} INFO - Temporary script location: /tmp/airflowtmp5wyyo29_/download_datadbsdrxcx
[2022-08-01 15:55:10,707] {{bash_operator.py:115}} INFO - Running command: 
  python3 $AIRFLOW_HOME/airflow/step1/data_download.py
[2022-08-01 15:55:10,712] {{bash_operator.py:122}} INFO - Output:
[2022-08-01 15:55:10,730] {{bash_operator.py:126}} INFO - python3: can't open file '/usr/local/airflow/airflow/step1/data_download.py': [Errno 2] No such file or directory
[2022-08-01 15:55:10,733] {{bash_operator.py:130}} INFO - Command exited with return code 2
[2022-08-01 15:55:10,738] {{taskinstance.py:1128}} ERROR - Bash command failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 134, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2022-08-01 15:55:10,739] {{taskinstance.py:1185}} INFO - Marking task as FAILED.dag_id=pipeline, task_id=download_data, execution_date=20220731T000000, start_date=20220801T155510, end_date=20220801T155510
[2022-08-01 15:55:20,626] {{logging_mixin.py:112}} INFO - [2022-08-01 15:55:20,626] {{local_task_job.py:103}} INFO - Task exited with return code 1
